arq5x/bedtools2

src/split/splitBed.cpp
src/split/splitBed.h
test/split/test-split.sh

As I said if  N< FOPEN_MAX, I now `fopen` all the N`FILE*`s, so there is no need to read the whole bed in memory.
I've also removed a dead code.
BTW Here is a nice example of piping with __GNU parallel__ (I used `wc` but one could imagine to `call samtools mpileup` for each BED... )
```
bedtools split -n 5 -p _tmp -a size -i test/intersect/sortAndNaming/bigTests/dbchr1.bed |\
cut -f 1 |  parallel wc -l '{}' 
7882 _tmp.00001.bed
7882 _tmp.00002.bed
7882 _tmp.00003.bed
7882 _tmp.00004.bed
7881 _tmp.00005.bed
```

[split]simple algorithm when n< FOPEN_MAX

---

src/genomeCoverageBed/genomeCoverageBed.cpp

We met a crash bug on following command:
bedtools genomecov -ibam /path/to/foo.bam -bg > x.bg
It crashed when processing 'chr9_gl000199_random'.
With the help of gdb, the crash was located on src/genomeCoverageBed/genomeCoverageBed.cpp:99
std::vector<DEPTH>().swap(_currChromCoverage);  // in BedGenomeCoverage::StartNewChrom
which indicated that there must have been memory access violation.
My best guess was at `BedGenomeCoverage::AddCoverage(int start, int end)`, and I tried to check `end` at runtime and found sometime it passed -1 value.
After the modification of this pull request, the problem should be solved.

Fix a crash bug (when end == -1).

---

Makefile
src/closestFile/closestMain.cpp
src/utils/FileRecordTools/Makefile
src/utils/NewChromsweep/NewChromsweep.h
src/utils/RecordOutputMgr/RecordOutputMgr.h
src/utils/general/CommonHelp.cpp
src/utils/general/CommonHelp.h
src/utils/general/ParseTools.h

Another batch of mostly warning fixes, many of which pertain to small issues in header files and so are repeated over and over during a full build. 
* Fix `namespace std`-related Clang warnings
* Fix `int2str()` overflow warning by recoding using `unsigned` to fix overflow bugs
* Minor build fixes

Minor warning and build fixes

---

src/utils/bedFile/bedFile.cpp

This came up on my Valgrind log while using the API.

Check for non-empty vector

---

src/split/splitBed.cpp
src/utils/FileRecordTools/Records/PlusFields.h

1. Another "unknown namespace" thing.
2. Use an `ostringstream` to format the split filename, forever avoiding the `size_t`-related warning.  This is an alternative to the C-style fix for this one in #250.

Minor warning fixes

---

Makefile

This is a downstream fix from the conda builds.

Allow for overwriting the prefix

---

test/merge/test-merge.sh

I think this patch resolves issue #327. The expected output for the test has been changed to reflect the actual error log printed by `merge`.

Fix issue 327: Changed expected output for merge.t11 to reflect the current output of merge

---

src/utils/KeyListOps/KeyListOpsMethods.cpp

* Start getMin()/getMax()/etc with the first entry in the list rather than with DBL_MAX or DBL_MIN.  I believe this really fixes [mergeBed max of '0', cast as a float gives 2.225073859e-308](https://groups.google.com/forum/#!searchin/bedtools-discuss/mergebed$20max/bedtools-discuss/RN2U64Y5Z6Q/HGXWGluGAwAJ) — which shows you how long I've been sitting on this, sorry about that!
* Take square root in stddev methods (cf #367)

Fix KeyListOps stddev and min/max methods

---

src/complementFile/complementFile.cpp
src/complementFile/complementFile.h

`_outputMgr` is not assigned by driver for an empty file.

Fix complement segfault for empty input intervals.

---

src/regressTest/RegressTest.cpp
src/sampleFile/sampleFile.cpp
src/utils/FileRecordTools/Records/RecordKeyList.cpp
src/utils/FileRecordTools/Records/RecordKeyList.h
src/utils/FileRecordTools/Records/RecordKeyVector.cpp
src/utils/FileRecordTools/Records/RecordKeyVector.h

A few tiny changes that prevent warnings from Intel's `icpc` compiler.  Motivated by [this seqanswers thread](http://seqanswers.com/forums/showthread.php?t=66910).

Prevent trivial Intel warnings

---

docs/content/tools/genomecov.rst

Minor typo correction in genomecov documentation.

Minor typo correction in documentation

---

docs/content/tools/getfasta.rst

Added tip for using single region BED files for fasta extraction using getfasta.
Currently if a single region BED file is provided without a newline character at the end of the region a blank output file is created without explanation of the error.

Added tip for extracting single region BED files using getfasta

---

src/fastaFromBed/fastaFromBed.cpp

I have added the feature as requested in #406. The name switch in getfasta till now only printed the name field. Now it prints the name field in bed file entry along with the chromosome name, start and end position along with the strand if strandedness is imposed.

Added feature: name, chromosome and position in fasta headers #406

---

src/utils/bedFile/bedFile.cpp
src/utils/bedFile/bedFile.h

This fixes the underlying _single region BED file is provided without a newline character_ problem in PR #403, so might be an alternative to adding the suggested tip.  I guess the problem exists everywhere one-line BED files might be used, so making the reader a little bit more resilient everywhere might be good.
----
A BED file with one record without a terminating newline character would not be returned as valid by GetNextBed(), because good() could not allow for the valid line already read by GetHeader() and stored in _bedLine.
Check the return value from getline() rather than checking good(). This is in general more robust than checking good() etc before reading.

Fix BedFile::GetNextBed()'s handling of missing newlines

---

src/bed12ToBed6/bed12ToBed6.cpp

Made the -n option not expect another string after it.
Also changed the comment saying that all options expect 2 strings.
See issue #466.

Fix issue #466 (bed12tobed6 handling -n parameter incorrectly)

---

src/multiBamCov/multiBamCov.cpp
src/utils/BamTools/src/api/internal/bam/BamMultiReader_p.cpp

Improve user experience for "multicov: Could not open input BAM files." by propagating the error messages from BamMultiReaderPrivate::Open to the users.
See issue: https://github.com/arq5x/bedtools2/issues/52

Improve user experience for "multicov: Could not open input BAM files."

---

src/utils/RecordOutputMgr/RecordOutputMgr.cpp

Only try to print a null record when the record type is known.
In case of an empty b file, the record type can not be determined.
This fixes "Segmentation fault with closestBed":
https://github.com/arq5x/bedtools2/issues/486

Bugfix bedtools closest: Do not segfault when b file is empty.

---

src/utils/Contexts/ContextBase.cpp
src/utils/Contexts/ContextIntersect.cpp

Fix setting of correct output type if -a is given after -b argment.
Set the correct output type based on the file given by -a, -abam or -i.
Before this patch, the output type was determined on the first
file. If -b was specified before -a, the first -b file would
be used instead of the -a file.
This fixes the first problem of issue #497:
"Switching order of -a and -b paramter in bedtools intersect when -b file is BAM file, outputs BAM header."

Fix file detection when switching a and b order

---

src/annotateBed/annotateBed.cpp

while keeping correct column delineation.

Fix trailing tab in header of annotateBed output

---

Makefile

Allow a user to specify the compiler externally. This is useful if downstream wants to build a set of packages with a specific compiler through a build framework. Also useful for contributors that want to compile-test with e.g. clang, xlC, icpc, etc.

Set CXX only if not pre-defined

---

src/utils/NewChromsweep/NewChromsweep.cpp
test/closest/sortAndNaming/test-sort-and-naming.sh
test/intersect/sortAndNaming/test-sort-and-naming.sh

Changed 're-reun' to 'rerun' in three error messages.

minor:  Fixed the same typo/misspelling in three locations.

---

src/maskFastaFromBed/Makefile
src/maskFastaFromBed/maskFastaFromBed.cpp
src/maskFastaFromBed/maskFastaFromBed.h
src/maskFastaFromBed/maskFastaFromBedMain.cpp

Add "-fullHeader" support to "bedtools maskfasta" so it prints
the full FASTA sequence name in the output FASTA file instead
of only the part before the space of TAB.
"-fullHeader" argument is also used by:
- bedtools getfasta
- bedtools nuc
for the same reason.
This fixes issue https://github.com/arq5x/bedtools2/issues/504:
"maskFastaFromBed discards additional annotation from FASTA header line"

Add "-fullHeader" support to "bedtools maskfasta".

---

src/utils/FileRecordTools/FileReaders/BufferedStreamMgr.cpp
src/utils/fileType/FileRecordTypeChecker.cpp

The older code in _bedFile.cpp_ and similar strips trailing CR characters so that (on Unix) bedtools can work on DOS-style or Unix-style files with CR-LF or LF line terminators.  Somewhere along the line, this feature seems to have disappeared.
We recently had a mysterious error with a 3-column BED file downloaded from Ensembl:
```
$ bedtools merge -I foo.bed
ERROR: file foo.bed has non positional records, which are only valid for 
the groupBy tool. Perhaps you are using a header line(s) that starts with 
something other than "#", "chrom", or "chr" (any case)?
```
This turned out to be because the file had CR-LF line terminators and was not being recognised as BED (as the third column contained non-digit characters — namely the CR!), but this took a long time to figure out.
I seem to …

Ignore CR characters at the ends of lines

---

docs/content/installation.rst

homebrew/science needs to be tapped first.

Clarify homebrew installation under OSX

---

src/utils/FileRecordTools/FileRecordMgr.h

- Resolves issue #538, making an implicit `std::` qualifier on a [`set` declaration](https://github.com/arq5x/bedtools2/blob/master/src/utils/FileRecordTools/FileRecordMgr.h#L126) explicit.
- Removes an unnecessary [`std` namespace import](https://github.com/arq5x/bedtools2/blob/master/src/utils/FileRecordTools/FileRecordMgr.h#L28) within [`FileRecordMgr.h`](https://github.com/arq5x/bedtools2/blob/master/src/utils/FileRecordTools/FileRecordMgr.h).

Resolve issue #538 and remove unnecessary namespace import

---

src/utils/BamTools/src/api/BamConstants.h
src/utils/BamTools/src/api/internal/io/HostAddress_p.cpp
src/utils/Contexts/ContextBase.cpp

Hello Aaron,
Some trivial fixes that silence warnings with current (Mac OS Sierra) Clang.  (One of which also silences a warning with GCC 6.3.)  Mostly in bamtools, including one fix ported from bamtools 2.4 and one that remains in current presumably-unmaintained bamtools, alas.

Various warning fixes

---

src/utils/FileRecordTools/Records/StrandQueue.cpp
src/utils/FileRecordTools/Records/StrandQueue.h

Hi, I'm a maintainer for the Homebrew package manager and we are encountering build problems on Xcode 9 (macOS 10.12 and 10.13).
The issue lies in `StrandQueue` and presumably the new version of `clang`'s stricter handling of `const` rules. I do not think `const` member functions are allowed to "see" the same view of a class that a non-`const` member function does--or the standard library's implementation of `priority_queue` has changed, leading to the following build errors when any `const` member function from the `StrandQueue` class is called:
```
StrandQueue.cpp:13:26: note: in instantiation of template class 'std::__1::priority_queue<Record *, std::__1::vector<const Record *, std::__1::allocator<const Record *> >, RecordPtrSortDescFunctor>' requested here
queueType *queue = new …
```

strandqueue: de-const for stricter Xcode 9 rules

---

src/shiftBed/shiftBed.cpp

When provided with a genome file, shift was still creating
intervals that extended past the last base pair.
See issue #599.

Stop shifting from extending past genome boundaries

---

src/utils/general/InflateStreamBuf.h

An updated version of the fix for #643. Tracking the buffer size avoids `realloc(buffer,0)` and thus fixes the buffering bug. This version also reduces the number of realloc() calls made overall, by reusing the existing buffer where possible. So a small speed increase (and no memory use increase, as each `buffin` GZBUFSIZ bytes mostly decompresses to a similar size).
No worries if you don't want to apply this one :smile:

InflateStreamBuf: Only realloc() when buffer is being enlarged

---

Makefile
src/bamToBed/bamToBed.cpp
src/bed12ToBed6/bed12ToBed6.cpp
src/getOverlap/getOverlap.cpp
src/nucBed/nucBed.cpp
src/pairToPair/pairToPair.cpp
src/randomBed/randomBed.cpp
src/randomBed/randomBed.h
src/utils/BamTools/include/BamAlignment.hpp
src/utils/BamTools/include/BamReader.hpp
src/utils/BamTools/include/BamWriter.hpp
src/utils/BamTools/include/SamHeader.hpp
src/utils/BamTools/include/api/BamAlignment.h
src/utils/BamTools/include/api/BamMultiReader.h
src/utils/BamTools/include/api/BamWriter.h
src/utils/BinTree/BinTree.cpp
src/utils/BinTree/BinTree.h
src/utils/FileRecordTools/FileReaders/InputStreamMgr.h
src/utils/bedFile/bedFile.h
src/utils/bedFilePE/bedFilePE.cpp

* Updates the `-I` entry in the makefile and the HTSlib include lines to `#include <htslib/sam.h>` etc. This is how HTSlib's headers are set up to be used, and doing this will facilitate bedtools using an external HTSlib should that become practical in future.
* Adds a `PRId_CHRPOS` macro based on `PRId64` for use when printfing `CHRPOS` values, preventing a bunch of warnings.
At present eleven header files definite the `CHRPOS` typedef and I've added `PRId_CHRPOS` to two of them. All these should probably be centralised in _BedtoolsTypes.h_ at some point.
* Some other minor warnings coming from header files.

Update HTSlib #include base; fix printf(…, CHRPOS, …) warnings

---

src/utils/BamTools/include/BamAlignment.hpp
src/utils/BamTools/include/SamHeader.hpp

Hi! While testing the macports port for v2.28.0, I noticed this version of bedtools does not build on older versions of xcode (7 and 8) without this include. Thanks.
-- Arjan

bedtools2: add stdlib.h include to make it compile on xcode 7 and 8

---

src/randomBed/randomBed.h
src/split/splitBed.cpp
src/utils/BinTree/BinTree.h
src/utils/bedFile/bedFile.h
src/utils/general/BedtoolsTypes.h

Fix the `__STDC_FORMAT_MACROS` thing by moving `PRId_CHRPOS` to BedtoolsTypes.h and including that header in the two headers that previously defined `PRId_CHRPOS`. As an alternative to #713 that centralises this mess in one place under the covers — #713's approach of adding it to CXXFLAGS in the Makefile is a little fragile if people happen to be overriding CXXFLAGS themselves.
Apologies for the oversight and the resulting inconvenience… 😞

Define __STDC_FORMAT_MACROS to fix build on old compiler environments

---

src/utils/fileType/FileRecordTypeChecker.cpp

I just updated the bedtools Debian package when this warning rushed across the screen.

Eliminate compiler warning size_t != int

---

src/bamToFastq/bamToFastq.cpp

When bamToFastq encountered multi-mapping reads it would throw many misleading and spurious warnings indicating that a paired-end read was not adjacent to it's mate as well as including the read in the resulting fastq every time a second mate read in encountered. This is a bug in the bamToFastq code as mentioned in issues #312 and #109 . 
This issue is easily solved since the bam file is already required to be namesorted, all of the reads are adjacent in the file. Thus the file must be read until the next read name is encountered or the file ends, saving only the most recent first and second mate records.

Fixed multimappers bug in bamToFastq

---

src/slopBed/slopBed.cpp
src/utils/Contexts/ContextBase.cpp
src/utils/Contexts/ContextBase.h
src/utils/FileRecordTools/FileReaders/BufferedStreamMgr.cpp
src/utils/FileRecordTools/FileReaders/BufferedStreamMgr.h
test/intersect/new_test-intersect.sh

For issue #767, the only thing is int overflow, change all size to use size_t, which suppose to be the right type for memory size.
For issue #768, It seems the original logic is overly complicated I've refactor them. And for chrom doesn't present, it treat the gnome size is unlimited. (Not sure if this is expected, but for v0.2.6 it behaves in this way).

Fix issue 767 and 768

---

src/annotateBed/annotateBed.cpp

Avoid looping SIZE_MAX times when `_bed->bedType` is 0; we can't just subtract 1 from an unsigned variable with value 0.
This still prints an extra tab when bedType is 0 as the code that prints the labels prefixes the first one with a tab, but as this is a degenerate case of an empty file it's not worth changing.
Happily, there are no other instances of `bedType - 1` in the code at present.

Fix issue 816: annotate -names on an empty input file

---

docs/content/advanced-usage.rst

I have updated here the first two `bedtools coverage` examples to reflect changes in the ordering of arguments for that command.
As I do not have experience with the `-abam` option, I did not change the command at https://github.com/arq5x/bedtools2/commit/91628aac2b171f54cacfc38fbe6da0f508450624#diff-0146c5f9d1549f0728ce970bf905d2d5R80 , but I suspect that may need be updating as well.

Update coverage docs in advanced-usage.rst

---

src/bedtools.cpp
src/utils/BamTools/include/BamReader.hpp
src/utils/BamTools/include/BamWriter.hpp

Closes issue #846 
Since all bedtools subcommand parse the parameter independently, a global setting is required for things like CRAM refs. This change allows global settings (particularly CRAM_REFERENCE) to be configured with parameters.

Allow cram reference passed with parameter

---

src/genomeCoverageBed/genomeCoverageBed.cpp
src/genomeCoverageBed/genomeCoverageBed.h
src/genomeCoverageBed/genomeCoverageMain.cpp

This adds a command-line option "-ignoreD" which will treat any Ds in the CIGAR string as being equivalent to M/X/=. In other words, coverage is calculated ignoring any local deletions.
The functionality to do this was already present in the code in [BlockedIntervals.cpp](https://github.com/arq5x/bedtools2/blob/67d5cd8f9ca10556688a8331a73cc8fc604191d1/src/utils/BlockedIntervals/BlockedIntervals.cpp#L42); this patch simply exposes that functionality to the command line.
For reference (including example SAM files), see issue #867.

Add command-line options for ignoring local deletions

---

src/utils/FileRecordTools/Records/Bed3Interval.cpp

Reset the zero size flag when reuse the bed record

---

src/utils/FileRecordTools/Records/Bed3Interval.cpp
src/utils/FileRecordTools/Records/Record.h

The recent PR #880's `print_record()` converted some iostreams code to use printf instead. It's printing `CHRPOS` values, and on macOS or with Clang this type is based on `long long` rather than `long`, so `%ld` produces warnings (and possibly failures on other platforms) and the code needs to use `PRId_CHRPOS` instead.
It needs an extra `#include` to use that, so it was easier to fix it in a PR than to describe what needed to be done to best make the `PRId_CHRPOS` definition available :smile:

Use PRId_CHRPOS to printf CHRPOS values

---

src/bamToFastq/bamToFastqMain.cpp

Hi there, 
Noticed this tiny tiny thing when trying to use bamToFastq: when no bam file is provided (or its given as a positional arugment) the error message asks for the `-bam` argument... which doesn't exist (it's -i).
This commit might save someone else three seconds of their life (and let me say I made a tiny contribution to one of my favourite pieces of software!)

Tiny tweak to error message when bamToFastq doesn't get a bam file

---

src/windowMaker/windowMakerMain.cpp

This fix is minor, but modifies the check of "--help" option.
Without this fix, the program outputs "ERROR: Unrecognized parameter" for "--help", which seems to be unintentional.

Fix the long help parameter check in makewindows

---

src/utils/GenomeFile/NewGenomeFile.cpp

This commit just improves the error message by inserting spaces around a genome file.

Modify the error message in loading a genome file

---

src/utils/GenomeFile/NewGenomeFile.cpp
src/utils/general/ParseTools.cpp
src/utils/general/ParseTools.h

Most parts of bedtools — e.g. the main BED file parsers — can accept either Unix- or Windows-style line termination, as they explicitly trim `'\n'` and `'\r'` characters from lines as they are read in. At present, reading in genome files does not do that, leading to obscure error messages such as encountered by the OP in #998.
This PR adds a utility function to trim any CR or LF characters at the end of a string, and uses it in `NewGenomeFile::loadGenomeFileIntoMap()` which did not previously accept Windows-style CRLF-delimited files. I didn't alter `GenomeFile`; hopefully most bedtools code uses the `New…` class!
There are several other file reading classes that do their own newline trimming. It's a low priority, but they could be altered to use this utility function too if desired.

Ignore Windows-style line termination in genome files

---

src/genomeCoverageBed/genomeCoverageBed.cpp
src/genomeCoverageBed/genomeCoverageMain.cpp
test/genomecov/mk-deep.py
test/genomecov/test-genomecov.sh

closes #371
the new test prints 1e6 for previous versions of bedtools.

fix coverage formatting when scale == 1

---

src/utils/Fasta/Fasta.cpp

Clang produces the following warning for _Fasta.cpp_ — and `idx_path` does indeed point to something no longer valid after the semicolon:
```
src/utils/Fasta/Fasta.cpp:38:28: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
const char *idx_path = (fname + ".fai").c_str();
^~~~~~~~~~~~~~~~
```
There are two other instances of the same warning, in _BamAncillary.cpp_, but that code is never used so doesn't matter too much.

Avoid dangling reference to temporary string object

---

src/utils/FileRecordTools/Records/Record.h
src/utils/NewChromsweep/NewChromsweep.cpp
src/utils/NewChromsweep/NewChromsweep.h
src/utils/general/ParseTools.cpp
src/utils/general/ParseTools.h

As noted in #1056 et al, on recent platforms _ParseTools.cpp_/_.h_ fail to compile due to `uint32_t` not being declared. The obvious fix is to add `#include <cstdint>` but we can tidy things up a bit by fixing this differently. This PR fixes that build failure and also fixes several warnings encountered with GCC 13:
Due to improvements in system and/or compiler header cleanliness, where previously _ParseTools.{cpp,h}_'s headers have included `<cstdint>` as a byproduct, this no longer occurs. Hence:
- Ordinary unsigned is appropriate for the int2str() variable anyway;
- Get CHRPOS from BedtoolsTypes.h instead of typedeffing it ourselves;
- ParseTools.cpp's isHeaderLine() does use uint32_t, so include `<cstdint>` from the .cpp file for good measure.
Other warnings:
- Assignment operators …

Fix various GCC 13 warnings and errors

---

src/utils/NewChromsweep/NewChromsweep.cpp
test/closest/sortAndNaming/test-sort-and-naming.sh
test/intersect/sortAndNaming/exp1
test/intersect/sortAndNaming/test-sort-and-naming.sh

Typo, but I think I'm going to start referring to maternal haplotypes as "chromomsomes"

typo fix: chromomsome

---

docs/index.rst

The link to the BedTools tutorial was incorrect. There’s an extra /bedtools/ in the URL currently linked to the documentation:
Current link: http://quinlanlab.org/tutorials/bedtools/bedtools.html
Actual URL: http://quinlanlab.org/tutorials/bedtools.html

Correcting link to the BedTools tutorial in index.rst
